name: Build and Deploy Submodule

on:
  push:
    branches:
      - release/namemaster

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Java environment (Maven in this case)
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # Build the specific submodule
    - name: Build submodule
      run: |
        mvn clean install spring-boot:repackage -pl spring-ai-alibaba-agent-example/playground-flight-booking -am

    # Build Docker image for the submodule
    - name: Build Docker image
      run: |
        docker build -t crpi-yzbqob8e5cxd8omc.cn-hangzhou.personal.cr.aliyuncs.com/jie7/longyouyou:latest ./spring-ai-alibaba-agent-example/playground-flight-booking

    # Login to Docker Hub
    - name: Log in to Aliyun Docker Registry
      run: |
        echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_REGISTRY_USERNAME }}" --password-stdin crpi-yzbqob8e5cxd8omc.cn-hangzhou.personal.cr.aliyuncs.com

    # Push the Docker image to Docker Hub (or another registry)
    - name: Push Docker image
      run: |
        docker push crpi-yzbqob8e5cxd8omc.cn-hangzhou.personal.cr.aliyuncs.com/jie7/longyouyou:latest
        
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Step 7: SSH 登录 ECS 服务器并部署
      - name: Deploy to ECS
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.ALIYUN_ECS_IP }}
          username: ${{ secrets.ALIYUN_ECS_USER }}
          key: ${{ secrets.ALIYUN_ECS_SSH_KEY }}
          script: |
            echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | sudo docker login --username "${{ secrets.DOCKER_REGISTRY_USERNAME }}" --password-stdin crpi-yzbqob8e5cxd8omc.cn-hangzhou.personal.cr.aliyuncs.com
            sudo docker pull crpi-yzbqob8e5cxd8omc.cn-hangzhou.personal.cr.aliyuncs.com/jie7/longyouyou:latest
            sudo docker stop longyouyou || true
            sudo docker rm longyouyou || true
            sudo docker run -d --name longyouyou -p 40081:40081 \
              -e DASHSCOPE_API_KEY=${{ secrets.DASHSCOPE_API_KEY }} \
              -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
              crpi-yzbqob8e5cxd8omc.cn-hangzhou.personal.cr.aliyuncs.com/jie7/longyouyou:latest
